package com.fczyz.jdbcdemo.service;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import com.fczyz.jdbcdemo.domain.ComputerGame;

public class ComputerGameManagerJDBC implements ComputerGameManager {

	private Connection connection;

	private String url = "jdbc:hsqldb:hsql://localhost/workdb";

	private String createTableComputerGame = "CREATE TABLE ComputerGame(id bigint GENERATED BY DEFAULT AS IDENTITY, title varchar(20) UNIQUE, release Date, price Double, multiplayer Boolean)";

	private PreparedStatement addComputerGameStmt;
	private PreparedStatement deleteAllComputerGamesStmt;
	private PreparedStatement getAllComputerGamesStmt;

	private Statement statement;

	public ComputerGameManagerJDBC() {
		try {
			connection = DriverManager.getConnection(url);
			statement = connection.createStatement();

			ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
			boolean tableExists = false;
			while (rs.next()) {
				if ("ComputerGame".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;
				}
			}

			if (!tableExists)
				statement.executeUpdate(createTableComputerGame);

			addComputerGameStmt = connection.prepareStatement("INSERT INTO ComputerGame (title, release, price, multiplayer) VALUES (?, ?, ?, ?)");
			deleteAllComputerGamesStmt = connection.prepareStatement("DELETE FROM ComputerGame");
			getAllComputerGamesStmt = connection.prepareStatement("SELECT id, title, release, price, multiplayer FROM ComputerGame");

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	public Connection getConnection() {
		return connection;
	}

	public void clearComputerGames() {
		try {
			deleteAllComputerGamesStmt.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	@Override
	public int addComputerGame(ComputerGame computergame) {
		int count = 0;
		try {
			addComputerGameStmt.setString(1, computergame.getTitle());
			addComputerGameStmt.setDate(2, computergame.getRelease());
			addComputerGameStmt.setDouble(2, computergame.getPrice());
			addComputerGameStmt.setBoolean(2, computergame.getMultiplayer());

			count = addComputerGameStmt.executeUpdate();

		} catch (SQLException e) {
			e.printStackTrace();
		}
		return count;
	}

	@Override
	public List<ComputerGame> getAllComputerGames() {
		List<ComputerGame> computergames = new ArrayList<ComputerGame>();

		try {
			ResultSet rs = getAllComputerGamesStmt.executeQuery();

			while (rs.next()) {
				ComputerGame g = new ComputerGame();
				g.setId(rs.getInt("id"));
				g.setTitle(rs.getString("title"));
				g.setRelease(rs.getDate("release"));
				g.setPrice(rs.getDouble("price"));
				g.setMultiplayer(rs.getBoolean("multiplayer"));
				computergames.add(g);
			}

		} catch (SQLException e) {
			e.printStackTrace();
		}
		return computergames;
	}

	@Override
	public void addAllComputerGames(List<ComputerGame> computergames) {

		try {
			connection.setAutoCommit(false);
			for (ComputerGame computergame : computergames) {
				addComputerGameStmt.setString(1, computergame.getTitle());
				addComputerGameStmt.setDate(2, computergame.getRelease());
				addComputerGameStmt.setDouble(1, computergame.getPrice());
				addComputerGameStmt.setBoolean(2, computergame.getMultiplayer());
				addComputerGameStmt.executeUpdate();
			}
			connection.commit();
			
		} catch (SQLException exception) {
			
			try {
				connection.rollback();
			} catch (SQLException e) {
				e.printStackTrace();
				//!!!! ALARM
			}
		}

	}


}
